#!/bin/bash
#
# This is a script to auto-install XRDP & XORGXRDP to Zorin 16.2
#
# After the installation, you will be able to run ZorinOs on a Hyper-V Enhanced Session.
# Enabling Display, Audio & Printers configuration, Clipboards for copy and paste, Smart cards, USB devices, Drives, Supported plug and play devices
#
# Many thanks to https://raw.githubusercontent.com/Hinara/linux-vm-tools/ubuntu20-04/ubuntu/20.04/install.sh
#
###############################################################################
# Use HWE kernel packages
#
HWE=""
#HWE="-hwe-22.04"

###############################################################################
echo "Let's update this PC"
#
if [ "$(id -u)" -ne 0 ]; then
    echo 'You must run this script with root privileges' >&2
    exit 1
fi

apt update && apt upgrade -y

if [ -f /var/run/reboot-required ]; then
    echo "You must reboot the PC to proceed with the installation." >&2
    echo "Please reboot and re-run this script to finish the install." >&2
    exit 1
fi

###############################################################################
# Open-source Remote Desktop Protocol Server (xrdp)
# http://xrdp.org/

# Hyper-V Key Value Pair (hv_kvp) Driver
# https://www.freebsd.org/cgi/man.cgi?query=hv_kvp&sektion=4

# Installing hv_kvp
apt install -y linux-tools-virtual${HWE}
apt install -y linux-cloud-tools-virtual${HWE}

# Installing xrdp
apt install -y xrdp

systemctl stop xrdp
systemctl stop xrdp-sesman

# Configuring installed XRDP ini files
# Use vsock transport
sed -i_orig -e 's/port=3389/port=vsock:\/\/-1:3389/g' /etc/xrdp/xrdp.ini

# Use rdp security
sed -i_orig -e 's/security_layer=negotiate/security_layer=rdp/g' /etc/xrdp/xrdp.ini

# Add script to setup the ZorinOS session properly
if [ ! -e /etc/xrdp/zorinos.sh ]; then
cat >> /etc/xrdp/zorinos.sh << EOF
#!/bin/sh
export GNOME_SHELL_SESSION_MODE=zorinos
export XDG_CURRENT_DESKTOP=zorin:GNOME
exec /etc/xrdp/startwm.sh
EOF
chmod a+x /etc/xrdp/zorinos.sh
fi

# Use the script to setup the ZorinOS session
sed -i_orig -e 's/startwm/zorinos/g' /etc/xrdp/sesman.ini

# Rename the redirected drives to 'shared-drives'
sed -i -e 's/FuseMountName=thinclient_drives/FuseMountName=shared-drives/g' /etc/xrdp/sesman.ini

# Changed the allowed_users
sed -i_orig -e 's/allowed_users=console/allowed_users=anybody/g' /etc/X11/Xwrapper.config

# Blacklist the vmw module
if [ ! -e /etc/modprobe.d/blacklist-vmw_vsock_vmci_transport.conf ]; then
  echo "blacklist vmw_vsock_vmci_transport" > /etc/modprobe.d/blacklist-vmw_vsock_vmci_transport.conf
fi

#Ensure hv_sock gets loaded
if [ ! -e /etc/modules-load.d/hv_sock.conf ]; then
  echo "hv_sock" > /etc/modules-load.d/hv_sock.conf
fi

# Configure the policy xrdp session
cat > /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla <<EOF
[Allow Colord all Users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF

# Reconfiguring services
systemctl daemon-reload
systemctl start xrdp

#
# End XRDP
###############################################################################

echo "Installation is complete."
echo "Reboot your machine to begin using XRDP."
echo "____________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_________________
________________________¶¶¶_______________________
________________________¶¶¶_______________________
___________¶¶___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶___¶¶__________
_________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶________
_________¶¶¶¶¶¶¶¶______¶¶¶¶¶_____¶¶¶¶¶¶¶¶¶________
__________¶¶¶___________¶¶¶___________¶¶¶_________
__________¶¶¶___________¶¶¶___________¶¶¶_________
________¶¶¶¶¶¶__________¶¶¶__________¶¶¶¶¶________
________¶¶¶¶¶¶__________¶¶¶__________¶¶¶¶¶________
________¶__¶_¶__________¶¶¶_________¶¶_¶_¶¶_______
_______¶¶_¶¶_¶¶_________¶¶¶_________¶¶_¶_¶¶_______
_______¶¶_¶¶__¶_________¶¶¶________¶¶__¶__¶¶______
______¶¶__¶¶__¶¶________¶¶¶________¶___¶___¶______
______¶___¶¶___¶¶_______¶¶¶_______¶¶___¶___¶¶_____
_____¶¶___¶¶___¶¶_______¶¶¶______1¶____¶____¶1____
____1¶____¶¶____¶¶______¶¶¶______¶1____¶____1¶____
____¶1____¶¶_____¶______¶¶¶_____¶¶_____¶_____¶¶___
___¶¶_____¶¶_____¶¶_____¶¶¶_____¶______¶______¶___
___¶______¶¶______¶¶____¶¶¶____¶¶______¶______¶¶__
__¶________¶_______¶____¶¶¶____¶_______¶_______¶__
¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶__¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶___¶¶¶__¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_____¶¶¶_____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶__
______¶¶¶¶¶¶¶¶¶¶___¶¶¶¶¶¶¶¶¶¶¶¶____¶¶¶¶¶¶¶¶¶______
________________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________
_______________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________
________________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________"
